"""Initial revision2

Revision ID: 1f8360be65b6
Revises: 4c634e5f82bd
Create Date: 2024-10-26 01:24:31.880760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1f8360be65b6'
down_revision: Union[str, None] = '4c634e5f82bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'game_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('game_state', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
